### ISSUE TITLE
Website needs new images

### ISSUE THREAD

**Issue by OH-UMM** [umm-5/umm-5.github.io#1]
While the construction gif has a [long and storied history](http://www.movingimage.us/exhibitions/2012/12/04/detail/under-construction/) and comes in [near-infinite varieties](http://www.textfiles.com/underconstruction/), it is perhaps not the best choice for our site.

A tip:

Make sure that the licensing on the image gives you permission to add them. An easy way to make sure if that is to choose Creative Commons-licensed images. You can find great re-usable images on Wikimedia Commons, at http://flickr.com/creativecommons, or by using the advanced search within Google Image Search, just to name a few options.

**Comment by emmasax1** [comment]
Assigned to @J-Ziegler
